# Generated by Django 5.0.6 on 2024-05-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_event_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
